- name: Set up node's network adapter
  template:
      src: files/interfaces
      dest: /etc/network/interfaces

- name: Update apt cache
  apt: update_cache=yes

- name: Install developer packages
  apt: 
    name:
      - python3
      - python3-pip
      - picocom
      - git
      - python3-venv
      - cmake
      - libglib2.0-dev
      - libcairo2-dev
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-3.0
      - libgirepository1.0-dev
    state: present

- name: Disable unused libraries
  copy:
      src: files/mrover.site
      dest: /home/{{ running_user }}/mrover.site

- name: Set Environment Variables
  copy:
      src: files/beaglebone.env
      dest: /etc/default/beaglebone.env

