#!/bin/bash

set -eo pipefail

FILEPATH=$(realpath "${0}")
DIR=$(dirname "${FILEPATH}")
JARVIS_ROOT=${DIR}/jarvis_files
JARVIS_VENV=${JARVIS_ROOT}/env
MBED_VENV=${JARVIS_ROOT}/mbed_env
PRODUCT_ENV=${DIR}/build/env

run_jarvis() {
    # Runs a Jarvis command using PyInvoke
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
    jarvis "--root=${DIR}" "$@"
    return $?
}

if [ ! -d "${JARVIS_VENV}" ]; then
    echo -n "Bootstrapping..."
    # Make virtualenv for Jarvis
    python3 -m venv "${JARVIS_VENV}"
    # shellcheck source=/dev/null
    source "${JARVIS_VENV}/bin/activate"
	pip install --upgrade pip >/dev/null
    pip install -r "${JARVIS_ROOT}/requirements.txt" >/dev/null
    pip install "${JARVIS_ROOT}/jarvis_cmd" >/dev/null
    echo "Done!"
fi

if [ "$#" -lt 1 ]; then
    run_jarvis --help
    exit 0
fi

if [ "$1" = "implode" ]; then
    if [ -d "${PRODUCT_ENV}" ]; then
        run_jarvis clean
    fi
    # Delete virtualenv
    cd "${DIR}"
    rm -rf "${JARVIS_VENV}"
    rm -rf "${MBED_VENV}"
    exit 0
fi

if [ "$1" = "exec" ]; then
    if [ -d "${PRODUCT_ENV}" ]; then
        # shellcheck source=/dev/null
        source "${PRODUCT_ENV}/bin/activate"
        shift
        exec "$@"
    else
        echo "You must build something in order to be able to exec a command."
    fi
    exit 0
fi

run_jarvis "$@"

