#!/bin/bash

# Focus in on the current window
WID=$(xdotool selectwindow)
xdotool windowfocus $WID

# Enter commands you want to be executed in the window here

# Run Perception
xdotool key type "./jarvis exec jetson/nav"
xdotool key KP_Enter

#Open a new tab for Obstacle LCM
xdotool key ctrl+shift+t
xdotool key type "./jarvis exec base_station/gui"
xdotool key KP_Enter

# Make window 1/4 of screen and align lower left
dimensions=$(./jarvis_files/jarvis_cmd/launchScripts/dim)
dim=($dimensions)
echo ${dim[0]}
dim[0]=$(expr ${dim[0]} / 2)
dim[1]=$(expr ${dim[1]} / 2)
echo ${dim[0]}
xdotool windowsize $WID ${dim[0]} ${dim[1]} 
xdotool windowmove $WID 0 0
xdotool windowminimize $WID
