#!/bin/bash

xdotool key --window $1 type "ssh mrover@10.1.0.1"
xdotool key --window $1 KP_Enter
sleep 1s
xdotool key --window $1 type "mrover"
xdotool key --window $1 KP_Enter
sleep 1s
xdotool key --window $1 type "cd ~/mrover-workspace"
xdotool key --window $1 KP_Enter
