#!/bin/bash

OS=$(uname)

if [ "${OS}" == "Darwin" ]; then
	BROWSER=open
elif [ "${OS}" == "Linux" ]; then
	BROWSER=xdg-open
fi

trap "exit" INT TERM ERR
trap "kill 0" EXIT

base_station_bridge &
${BROWSER} http://localhost:8000/
(cd {{ bsgui_dir }} && python -m http.server)
