#!/bin/bash

# Focus in on the current window
WID=$(xdotool selectwindow)
xdotool windowfocus $WID

# Enter commands you want to be executed in the window here

# Run Localization
xdotool key type "sudo ./jarvis exec jetson/gps"
xdotool key KP_Enter

#Open a new tab for Obstacle LCM
xdotool key ctrl+shift+t
# Check If need to ssh first
if [[ $1 ]]; then
    ./jarvis_files/launchScripts/ssh $WID
fi
xdotool key type "./jarvis exec jetson/mp9250_bridge"
xdotool key KP_Enter

#Open a new tab for Obstacle LCM
xdotool key ctrl+shift+t
# Check If need to ssh first
if [[ $1 ]]; then
    ./jarvis_files/launchScripts/ssh $WID
fi
xdotool key type "./jarvis exec jetson/filter"
xdotool key KP_Enter

# Make window 1/4 of screen and align upper right
dimensions=$(./jarvis_files/launch_scripts/dim)
dim=($dimensions)
dim[0]=$(expr ${dim[0]} / 2)
dim[1]=$(expr ${dim[1]} / 2)
xdotool windowsize $WID ${dim[0]} ${dim[1]} 
xdotool windowmove $WID ${dim[0]} 0 
xdotool windowminimize $WID
