#!/bin/bash

# Execute command in specified window
# Param1: Command to execute
# Param2: Window ID
window_execute() {
    xdotool key --window $2 type "$1"
    xdotool key --window $2 KP_Enter
}

# ssh check
# Param1: command to execute
# Param2: Window ID to execute command in
# Param3: ssh flag passed to the file
execute_command() {
    window_execute "echo Execute this!" $2
    if [ "$3" == "ssh" ]
    then
        ./jarvis_files/launch_scripts/ssh "none" $2 10.1.0.2
    else
        window_execute "$1" $2
    fi
}



# Focus in on the current window
WID=$(xdotool selectwindow)
xdotool windowfocus $WID

# Enter commands you want to be executed in the window here

# Run Navigation
execute_command "./jarvis exec jetson/nav" $WID $1

# Make window 1/4 of screen and align lower left
# dimensions=$(./jarvis_files/launch_scripts/dim)
# dim=($dimensions)
# dim[0]=$(expr ${dim[0]} / 2)
# dim[1]=$(expr ${dim[1]} / 2)
# xdotool windowsize $WID ${dim[0]} ${dim[1]} 
# xdotool windowmove $WID 0 0
# xdotool windowminimize $WID
