#!/bin/bash
# Param1: Commmand to execute
# Param2: Window ID
# Param3: IP Address
xdotool key --window $2 type "ssh mrover@$3"
xdotool key --window $2 KP_Enter
sleep 1s
xdotool key --window $2 type "mrover"
xdotool key --window $2 KP_Enter
sleep 1s
xdotool key --window $2 type "cd ~/mrover-workspace"
xdotool key --window $2 KP_Enter
