#!/bin/bash

xdotool key --window $1 type "ssh -X mrover@$2"
xdotool key --window $1 KP_Enter
sleep 1s
xdotool key --window $1 type "mrover"
xdotool key --window $1 KP_Enter
sleep 1s
xdotool key --window $1 type "cd ~/mrover-workspace"
xdotool key --window $1 KP_Enter
