---
- hosts: all
  become: yes
  vars:
    ubuntu_release: bionic
    workspace_dir: /home/mrover/mrover-workspace
    user: mrover
    ansible_python_interpreter: /usr/bin/python3
  roles:
  - jetson_dev
  - base_station_dev
  - base_station_networks
  - base_station_services
  tasks:
  - name: Wait for networkmanager to come back up
    wait_for: timeout=25
  - name: Install chromium
    apt: name=chromium-browser state=present
