---
- hosts: all
  become: yes
  gather_facts: False
  vars:
      ubuntu_release: bionic
      running_user: mrover
      home_dir: /home/mrover
      workspace_dir: /home/mrover/mrover-workspace
      ansible_python_interpreter: /usr/bin/python3
  roles:
  - jetson_dev
  - jetson_nano_networks
  - jetson_nano_services
  tasks:
  - name: Add odrive udev rules
    shell: | 
            sed 'N a SUBSYSTEM=="usb", ATTR{idVendor}=="1209", ATTR{idProduct}=="0d[0-9][0-9]", MODE="0666"' /etc/udev/rules.d/91-odrive.rules
            udevadm control --reload-rules
            udevadm trigger