---
- hosts: all
  become: yes
  gather_facts: False
  vars:
      ubuntu_release: bionic
      running_user: mrover
      home_dir: /home/mrover
      workspace_dir: /home/mrover/mrover-workspace
      ansible_python_interpreter: /usr/bin/python3
  roles:
  - jetson_dev
  - jetson_networks
  - jetson_services
  tasks:
  - name: Give {{ running_user }} all port permissions
    shell: | 
            usermod -a -G tty {{ running_user }} 
            usermod -a -G dialout {{ running_user }}
            systemctl disable nvgetty.service
  - name: Reboot
    command: reboot