---
- hosts: all
  become: yes
  vars:
      raspian_release: stretch
      running_user: pi
      workspace_dir: /home/pi/mrover-workspace
      ansible_python_interpreter: /usr/bin/python3
  roles:
  - pis
