- name: Install CV packages
  apt: 
    name:
      - libjansson-dev
      - libboost-dev
      - imagemagick
      - libtinyxml-dev
      - cmake
      - build-essential
      - yarn
      - mercurial
    state: present

# Install nodejs 16
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 16node.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present