- name: Install CV packages
  apt: 
    name:
      - libjansson-dev
      - libboost-dev
      - imagemagick
      - libtinyxml-dev
      - cmake
      - build-essential
      - nodejs
      - yarn
      - mercurial
    state: present
