- name: Install CV packages
  apt: name={{ item }} state=present
  with_items:
  - libjansson-dev
  - libboost-dev
  - imagemagick
  - libtinyxml-dev
  - cmake
  - build-essential
  - nodejs
  - yarn
  - mercurial
